# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Test backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
    JWT_SECRET: secret
    DB_USER: lion
    DB_PASSWORD: password
    DB_HOST: 127.0.0.1
    DB_PORT: 3306
    DB_NAME: raven_test
    SERVER_PORT: 8080
    RAVE_SECRET: secret
    TRX_SECRET: mysecret
    TEST_DEFAULT_BALANCE: 100
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout Git
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
      - name: Get redis
        run: docker pull redis:6.0
       
      - name: Setup yarn
        run: npm install -g yarn
      - name: mysql
        run: docker pull mysql:8.0

      - name: Docker testcontainers/ryuk:0.3.2
        run: docker pull testcontainers/ryuk:0.3.2

      - name: Install Packages
        run: yarn
      
      - name: Run tests
        run: yarn run tests
